# Generated by Django 2.2.4 on 2021-05-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0013_auto_20210503_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='submittedProfilePicImages/', verbose_name=''),
        ),
    ]
